version: '3'

services:
  nucypher-alice:
    command: /usr/local/bin/nucypher alice run --dev --network eth_denver --teacher-uri 18.217.28.35:9151
    environment: 
      - NUCYPHER_SENTRY_LOGS=0
    image: nucypher:latest
    container_name: nucypher-alice
    ports:
      - "8151:8151"
    build:
      context: "$NUCYPHER_HOME"
      dockerfile: "$NUCYPHER_HOME/deploy/docker/Dockerfile"
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

  nucypher-bob:
    command: nucypher bob run --dev --network eth_denver --teacher-uri 18.217.28.35:9151
    environment: 
      - NUCYPHER_SENTRY_LOGS=0
    image: nucypher:latest
    container_name: nucypher-bob
    ports:
      - "11151:11151"
    build:
      context: "${NUCYPHER_HOME}"
      dockerfile: $NUCYPHER_HOME/deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

  nucypher-enrico:
    command: '/usr/local/bin/get-alices-key'
    environment:
      - NUCYPHER_SENTRY_LOGS=0
    depends_on:
      - nucypher-alice
    image: nucypher:latest
    container_name: nucypher-enrico
    ports:
      - "5151:5151"
    build:
      context: "${NUCYPHER_HOME}"
      dockerfile: $NUCYPHER_HOME/deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

