version: '3'

services:
  nucypher-alice:
    command: /usr/local/bin/nucypher alice run --dev --network eth_denver --teacher-uri 18.217.28.35.9151
    image: nucypher:latest
    container_name: nucypher-alice
    ports:
      - "9151:9151"
    build:
      context: "${NUCYPHER_HOME}"
      dockerfile: $NUCYPHER_HOME/deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

  nucypher-bob:
    command: nucypher bob run --dev --network eth_denver --teacher-uri 18.217.28.35:9151
    image: nucypher:latest
    container_name: nucypher-bob
    build:
      context: "${NUCYPHER_HOME}"
      dockerfile: $NUCYPHER_HOME/deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

  nucypher-enrico:
    command: nucypher enrico run --policy-encrypting-key 035764934b643f0655815da52a116c1ac218938a4a87474d4c31c53836fbba1319
    image: nucypher:latest
    container_name: nucypher-enrico
    build:
      context: "${NUCYPHER_HOME}"
      dockerfile: $NUCYPHER_HOME/deploy/docker/Dockerfile
    volumes:
      - ~/.local/share/nucypher:/nucypher
    stdin_open: true
    tty: true

